### ISSUE TITLE
Twitch OAuth Credentials leak

### ISSUE THREAD

**Issue by JeromeJ** [GameDevLiege/GameDevTwitchPlays12#26]
https://github.com/GameDevLiege/GameDevTwitchPlays12/blob/eb8a9f725ff0079f09cbfcba9fd9ab9f5f9071a0/Assets/_GameDevTwitchPlays12/Teams/Team%20Twitch/Module%201/Scripts/Plugs/TwitchIRC/AutoConnectTwitchIRC.cs#L17

@JamsCenter Pourquoi avoir utiliser les `PlayerPrefs` ici ?
Ils sont set mais jamais get (il me semble...).

Si OK, je retire ces 3 lignes là et je met le OAuth dans un `ScriptableObject` qui ne sera auto-ignored.

**Comment by JeromeJ** [comment]
I thought maybe I could go on your fork and make you a pull request but I'm not finding where yours is… :/

**Comment by EloiStree** [comment]
The Twitch IRC of the Unity Asset store was using PlayerPrefs to register the connection id and was using a scene to set up the info.  As me made a auto-connect script we don't use it anymore.
By precaution in case we were missing information on the plug-in use we decide to set the data anyway. Just in case.

I can remove it you you desire. 
Use a scriptable object can be a solution.
But the scriptable object is in edit mode.
The user need to be able to configure that in a external file or in the config scene.

**Comment by JeromeJ** [comment]
The ScriptableObject wouldn't be to store the data over Play mode :)
Just to not commit your credentials in your git repository.
