### ISSUE TITLE
Twitch have anti-spam system

### ISSUE THREAD

**Issue by EloiStree** [GameDevLiege/GameDevTwitchPlays12#27]
Twitch have a anti-spam system: a command can't be call more then one time every 30 seconds.
Possible solution:
- Allow the user to write !up 3, ! down 2, !up 4 
- Allow the user to write !move 5 18

**Comment by TriturusVulgaris** [comment]
First option : Allow the user to write !up 3, ! down 2, !up 4

**Comment by JeromeJ** [comment]
Can't this be interrupted?

Like, while my mole is (still) moving up, can I change my mind and tell it to now go right?
(I think it should... beware of the delay thou)
